#!/usr/bin/bash

status="show"
y_lim=7

while :
do
    y=$(xdotool getmouselocation | awk '{print $2}' | cut -d: -f2)

    if [ "$y" -lt "$y_lim" ] && [ $status == "hide" ]; then
        polybar-msg cmd show > /dev/null
        status="show"
    elif [ "$y" -gt "$y_lim" ] && [ $status == "show" ]; then
        polybar-msg cmd hide > /dev/null
        status="hide"
    fi

    sleep 0.9
done
