#!/bin/sh

# If refreshing bspwm, remove all previous rules to prevent doubling up.
bspc rule -r "*"

#LAUNCHERS
"$HOME/.config/bspwm/autostart.sh"


#BSPWM configuration
#bspc config border_radius        	8 # needs patch
bspc config border_width         	2
bspc config window_gap           	3
bspc config top_padding          	1
bspc config bottom_padding       	1
bspc config left_padding         	1
bspc config right_padding        	1
bspc config single_monocle       	false
#bspc config click_to_focus       	true
bspc config split_ratio          	0.50
bspc config borderless_monocle   	true
bspc config gapless_monocle      	true
#bspc config focus_by_distance    	true
bspc config focus_follows_pointer 	false
#bspc config history_aware_focus  	true
bspc config pointer_modifier 		mod4
bspc config pointer_action1 		move
bspc config pointer_action2 		resize_side
bspc config pointer_action3 		resize_corner
bspc config remove_disabled_monitors 	true
bspc config remove_unplugged_monitors 	true
bspc config merge_overlapping_monitors 	true

#BSPWM coloring
bspc config normal_border_color		"#4c566a"
bspc config active_border_color		"#1e1e1e"
bspc config focused_border_color	"#00ff84"
bspc config presel_feedback_color	"#00ff84"
#bspc config urgent_border_color 	"#dd2727"


#AutoConfig monitor
if [ "$(grep -w mirror_mode "$HOME/.my_settings" | awk '{print $2}')" -eq "1" ]; then
    bspc monitor -d 1 2 3 
else
    "$HOME/.config/bspwm/scripts/multimonitor" 
fi

#Fullscreen applications
bspc rule -a Vlc state=fullscreen
bspc rule -a VirtualBox Manager state=fullscreen
bspc rule -a VirtualBox Machine state=fullscreen

#Floating applications
bspc rule -a Arandr state=floating
bspc rule -a feh state=floating
bspc rule -a Matplotlib state=floating center=true
bspc rule -a Xarchiver state=floating center=true
bspc rule -a Pavucontrol state=floating center=true
bspc rule -a Signal state=floating center=true rectangle=670x514+0+0
bspc rule -a TelegramDesktop state=floating center=true rectangle=309x514+0+0


#open applications on specific workspaces
#bspc rule -a Google-chrome desktop='^1' follow=on
#bspc rule -a vlc desktop='^6'  follow=on
#bspc rule -a mpv desktop='^6'  follow=on
#bspc rule -a Thunar desktop='^8' follow=on

###External rules
bspc config external_rules_command ~/.config/bspwm/scripts/external_rules_command_old
